# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
